- name: Wait for systems to boot up and cloud-init to complete
  hosts: all
  gather_facts: no
  any_errors_fatal: true
  tasks:
    - name: Wait up to 300 seconds
      wait_for_connection:
        delay: 3
        sleep: 5
        timeout: 300

    - name: Gather all facts of cloud init
      community.general.cloud_init_data_facts:
      register: result

    - name: Wait for cloud init to finish
      community.general.cloud_init_data_facts:
        filter: status
      register: res
      until: "res.cloud_init_data_facts.status.v1.stage is defined and not res.cloud_init_data_facts.status.v1.stage"
      retries: 50
      delay: 5

- name: Configure systems
  hosts: dse
  any_errors_fatal: true
  become: true
  gather_facts: true
  gather_subset:
    - "distribution"
    - "distribution_release"
    - "distribution_major_version"
    - "distribution_version"
    - "os_family"
  roles:
    - ansible_role_configure_os


- name: Install and configure DSE
  hosts: dse
  any_errors_fatal: true
  become: true
  become_method: sudo
  vars:
    #dse_ver_major: 6.8
    #dse_ver_minor: 44
    #dse_cluster_name: testcluster
    #dse_syslog_dir: /var/log/cassandra
    #dse_data_homedir: /opt/dse_data
  roles:
    - ansible_role_dse

## Check DSE version and C* version
- hosts: dse
  tasks:
  - name: Check DSE version
    ansible.builtin.command:
      cmd: dse -v
    register: _dse_ver
  - debug:
     msg: "DSE Version: {{ _dse_ver.stdout }}"
