- name: Install Java 8, libaio, and python
  ansible.builtin.apt:
    name:
      - "{{ openjdk_package }}"
      - "{{ libaio_package }}"
      - "{{ python_package }}"
    state: present
    update_cache: yes
    lock_timeout: 120
  register: apt_res
  retries: 60
  until: apt_res is success