- name: Update apt packages
  ansible.builtin.apt:
    update_cache: yes

- name: Install Java 8
  ansible.builtin.apt:
    name: "{{ openjdk_package }}"
    state: present

- name: Install libaio
  ansible.builtin.apt:
    name: "{{ libaio_package }}"
    state: present

- name: Install python
  ansible.builtin.apt:
    name: "{{ python_package }}"
    state: present