- name: Print distribution
  ansible.builtin.debug:
    msg: "{{ ansible_distribution }} - {{ ansible_distribution_version }}"

- name: Look for the most specific OS vars
  include_vars: "{{ item }}"
  loop: "{{ query('first_found', { 'files': files, 'paths': paths }) }}"
  vars:
    files:
      - "{{ ansible_distribution }}-{{ ansible_distribution_version }}.yml"
      - "{{ ansible_distribution }}-{{ ansible_distribution_major_version }}.yml"
      - "{{ ansible_distribution }}.yml"
    paths:
      - vars

- name: Configure debian
  ansible.builtin.include_tasks: ansible_task_configure_debian.yml
  when: ansible_distribution == "Debian" or ansible_distribution == "Ubuntu"

