- name: Add DataStax Enterprise repository
  ansible.builtin.apt_repository:
    repo: deb https://debian.datastax.com/enterprise stable main
    state: present
    filename: google-chrome

- name: Add the DataStax repository key
  ansible.builtin.apt_key:
    url: "https://debian.datastax.com/debian/repo_key"
    state: present

- name: Install DSE version {{ dse_ver_target }}
  when: dse_ver_major is version('5.1', '>=')
  ansible.builtin.apt:
    name: "{{ item }}"
    state: present
    update_cache: yes
  with_items:
    - "dse-libcassandra={{ dse_ver_target }}-1"
    - "dse-libgraph={{ dse_ver_target }}-1"
    - "dse-libhadoop2-client={{ dse_ver_target }}-1"
    - "dse-libhadoop2-client-native={{ dse_ver_target }}-1"
    - "dse-liblog4j={{ dse_ver_target }}-1"
    - "dse-libtomcat={{ dse_ver_target }}-1"
    - "dse-libsolr={{ dse_ver_target }}-1"
    - "dse-libspark={{ dse_ver_target }}-1"
    - "dse={{ dse_ver_target }}-1"
    - "dse-full={{ dse_ver_target }}-1"
