## Configure JVM options
- name: Print host memory size
  ansible.builtin.debug:
    var: ansible_memtotal_mb

- name: Validate host memory size is at least 48GB
  ansible.builtin.assert:
    fail_msg: "hardcoded JVM options require at least 48GB memory"
    that:
      - ansible_memtotal_mb >= 48000

- name: remove last line
  ansible.builtin.lineinfile:
    path: /etc/dse/cassandra/jvm-server.options
    regexp: "# The newline in the end of file is intentional"
    state: absent

- name: Add JVM options
  ansible.builtin.lineinfile:
    path: /etc/dse/cassandra/jvm-server.options
    insertafter: EOF
    line: |
      # Additional JVM options added by the ansible-dse playbook
      -XX:+UseG1GC
      -XX:G1RSetUpdatingPauseTimePercent=5
      -XX:MaxGCPauseMillis=300
      -XX:InitiatingHeapOccupancyPercent=70 -Xms31G -Xmx31G
      
      # The newline in the end of file is intentional
