## Configure JVM options
- name: Print host memory size in MB
  ansible.builtin.debug:
    var: ansible_memtotal_mb

- name: Calculate memory in GB
  ansible.builtin.set_fact:
    ansible_memtotal_gb: "{{ (ansible_memtotal_mb / 1024.0) | round(2, 'floor') }}"

- name: Print host memory size in GB
  ansible.builtin.debug:
    var: ansible_memtotal_gb

- name: Validate host memory size is at least 8GB
  ansible.builtin.assert:
    fail_msg: "hardcoded JVM options require at least 8GB memory"
    that:
      - ansible_memtotal_gb >= 8

- name: Calculate JVM memory in GB
  ansible.builtin.set_fact:
    jvm_memory_gb: "{{ min(32, ((ansible_memtotal_gb / 2) | round | int) }}"

- name: Print calculated JVM memory size in GB
  ansible.builtin.debug:
    var: jvm_memory_gb

- name: remove last line
  ansible.builtin.lineinfile:
    path: /etc/dse/cassandra/jvm-server.options
    regexp: "# The newline in the end of file is intentional"
    state: absent

- name: Add JVM options
  ansible.builtin.lineinfile:
    path: /etc/dse/cassandra/jvm-server.options
    insertafter: EOF
    line: |
      # Additional JVM options added by the ansible-dse playbook
      -XX:+UseG1GC
      -XX:G1RSetUpdatingPauseTimePercent=5
      -XX:MaxGCPauseMillis=300
      -XX:InitiatingHeapOccupancyPercent=70 
      -Xms{{ jvm_memory_gb }}G 
      -Xmx{{ jvm_memory_gb }}G
      
      # The newline in the end of file is intentional
