- name: Print distribution
  ansible.builtin.debug:
    msg: "{{ ansible_distribution }} - {{ ansible_distribution_version }}"

- name: Look for the most specific OS vars
  include_vars: "{{ item }}"
  loop: "{{ query('first_found', { 'files': files, 'paths': paths }) }}"
  vars:
    files:
      - "{{ ansible_distribution }}-{{ ansible_distribution_version }}.yml"
      - "{{ ansible_distribution }}-{{ ansible_distribution_major_version }}.yml"
      - "{{ ansible_distribution }}.yml"
    paths:
      - vars

- name: Set DSE version
  ansible.builtin.set_fact:
    ver_major: "{{ dse_ver_major | default(default_dse_ver_major) }}"
    ver_minor: "{{ dse_ver_minor | default(default_dse_ver_minor) }}"
    cluster_name: "{{ dse_cluster_name | default(default_dse_cluster_name) }}"

- name: Print DSE version
  ansible.builtin.debug:
    msg: "Requested DSE version: {{ ver_major }}.{{ ver_minor }}"

- name: Set variables
  ansible.builtin.set_fact:
    dse_ver_target: "{{ ver_major }}.{{ ver_minor }}"
    data_file_directories: "{{ dse_data_homedir | default(default_dse_data_homedir) }}/cassandra"
    commitlog_directory: "{{ dse_data_homedir | default(default_dse_data_homedir) }}/commitlog"
    saved_caches_directory: "{{ dse_data_homedir | default(default_dse_data_homedir) }}/saved_cahces"
    hints_directory: "{{ dse_data_homedir | default(default_dse_data_homedir) }}/hints"
    cdc_raw_directory: "{{ dse_data_homedir | default(default_dse_data_homedir) }}/cdc_raw"
    metadata_directory: "{{ dse_data_homedir | default(default_dse_data_homedir) }}/metadata"

- name: Create seed list
  ansible.builtin.include_tasks: ansible_task_create_seed_list.yml

- name: Mount disks
  ansible.builtin.include_tasks: ansible_task_mount_disks.yml

- name: Install DataStax binaries
  ansible.builtin.include_tasks: ansible_task_install_dse_binaries.yml

- name: Update DataStax configuration
  ansible.builtin.include_tasks: ansible_task_update_configuration.yml

- name: Start DataStax seed nodes
  ansible.builtin.include_tasks: ansible_task_start_seed_nodes.yml
  when: seed | bool

- name: Start DataStax others nodes
  ansible.builtin.include_tasks: ansible_task_start_other_nodes.yml
  when: not (seed | bool)