- name: Create seed list
  ansible.builtin.include_tasks: ansible_task_create_seed_list.yml

- name: Mount disks
  ansible.builtin.include_tasks: ansible_task_mount_disks.yml

- name: Install DataStax binaries
  ansible.builtin.include_tasks: ansible_task_install_dse_binaries.yml